version: "3.9"
services:
  web:
    image: webapi/account:1.0
    container_name: account-api
    build: 
      context: ./account-api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - ./cert/aspnetapp.pfx:/cert/aspnetapp.pfx:ro

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql-db
    user: root
    command: /bin/bash ./entrypoint.sh
    environment:
      SA_PASSWORD: "TestPwd.098"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - ./database/docker-entrypoint.sh:/entrypoint.sh
      - ./database/docker-db-init.sh:/db-init.sh
      - ./database/create-db.sql:/db-init.sql

  redis:
    image: "redis"
    container_name: session-store
    ports:
      - "6379:6379"
