version: "3.9"
services:
  web:
    image: webapi/account:1.0
    container_name: account-api
    build: 
      context: ./code
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql-db
    user: root
    command: /bin/bash ./entrypoint.sh
    environment:
      SA_PASSWORD: "TestPwd.098"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - ./db-init/docker-entrypoint.sh:/entrypoint.sh
      - ./db-init/docker-db-init.sh:/db-init.sh
      - ./db-init/create-db.sql:/db-init.sql

  redis:
    image: "redis"
    container_name: session-store
    ports:
      - "6379:6379"
